version: '3.2'

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
  pgadmin-data:
    driver: local

services:
  postgres:
    image: postgres:12-alpine
    tty: true
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    depends_on:
      - postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - '8081:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@test.com'
      PGADMIN_DEFAULT_PASSWORD: 'secret'
    networks:
      - app-network